import { Poppins } from 'next/font/google';
import "./globals.css";
import Header from "@/components/Header/Header";

const poppins = Poppins({
  weight: ['300','400', '500', '600', '700'], 
  subsets: ['latin'], 
  display: 'swap', 
});

export const metadata = {
  title: "Educational Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
